### ISSUE TITLE
Non `Module` attributes in class definitions

### ISSUE THREAD

**Issue by dan-fritchman** [dan-fritchman/Hdl21#38]
The class-based `Sim` definitions have a bit different rules from `Module` and `Bundle`.  
Wondering whether we should move to them. 

## The Parts in Common 

Each of Hdl21's class-decorated types `Module`, `Bundle`, and `Sim` are really organized containers of a small set of types. `Module` stores signals, instances, etc; `Sim` stores simulation attributes such as analyses and options. Class attributes of other types - e.g. integers, `TabError`s, `flask.App`s, anything - are "not allowed". The decorator functions make special exemptions for fields named with the Python language convention for private attributes, the preceding underscore. 

## The Differences 

The differences lie in what happens when encountering any of these unsupported types in the class body. 

`Module ` and `Bundle` immediately throw errors. E.g.:  

```python
@h.module
class HasInt:
  i = 5
  s = h.Signal(width=i)

@h.module
class HasMethod:
    def fail(self):
        ...

@h.bundle
class HasTabError:
    tab_error = TabError()
```

All produce `RuntimeError`s.  
Note these are all allowed if their attribute names are prepended with underscores, e.g.: 

```python
@h.module
class HasInt:
  _i = 5 # Now I'm "private"
  s = h.Signal(width=_i) # And this works
```

The `sim` decorator, in contrast, does not immediately throw an error. It allows these values to be created, and referred to by later ones. But it does not store them on the ultimate `Sim` definition. E.g.  

```python
@h.sim
class SimHasInt:
  t = 5e-9 
  tran = Tran(tstop=t) # This works
```

Here the attribute `t` can be referred to in the attribute `tran`. But the `Sim` object ultimately returned will not include `t`, only `tran`. I.e.: 

```python 
assert isinstance(SimHasInt.tran, Tran) # "Passes" (kinda)*
SimHasInt.t # Fail! AttributeError
```

Asterisk: `Sim` doesn't have the `getattr`-magic lookups of this sort. But the point is that `SimHasInt` does include a `Tran` object named `tran`.

## Potential Third Way 

The obvious alternative would be to just store everything, of any type, however the user wants.  
I don't want to do this.  
I want to maintain each of the structured Hdl types as strictly typed containers, in which Hdl21 knows all of the types, their relationships, and where to find all the attributes. We do lots of manipulating these attributes behind the scenes - such might be a description of the entire "elaboration" process. And I don't want to either (a) burden the users with organizing them, or (b) search the entire namespace for each one. 

## Proposal 

I think I like the `Sim` way best.

**Comment by growly** [comment]
It's not clear why one way or the other would be advantageous (or disadvantageous) to a user. Insofar as a DSL is valuable in the first place because it forces you to express only as much and as little as you need, I think there's value in constraining the types of attributes and limiting their visibility.

Whether those attributes outlive "elaboration" might become a matter of convenience: e.g. will users be able to write tests than depend on those attributes?

Whether errors are caught while ingesting a class body or later while doing some "elaboration" step isn't immediately clear. What is the difference to the designer's flow? Are they going to be iterating on describing a class to get it right or are they going to be iterating on their entire HDL description to get it right? I don't know.

(Are other polymorphism-esque conveniences going to be available, like derived classes (Modules)?)

**Comment by dan-fritchman** [comment]
Outlook: before #53
