### ISSUE TITLE
Netlist Subcircuit Name

### ISSUE THREAD

**Issue by yrrapt** [dan-fritchman/Hdl21#96]
Is there a way to specify the subcircuit name when exporting to netlist?

The use case is generating a netlist for LVS. In this case the subcircuit name needs to match the layout cell name exactly.

Thanks in advance

**Comment by dan-fritchman** [comment]
So - 

* Non-generated Modules should be netlisted with their name as-is. This is not necessarily ideal long-term since it can produce naming conflicts, but does help your goals here.
* Generated modules mix their parameter values into their name

Assuming the question is about the latter, two things come to mind:

1. Wrap the generated module in an un-generated one
2. Just… change the name field? But also don’t tell anyone I said so. Modifying generated modules is generally discouraged, largely bc they are cached. But, if you know enough to avoid that being a problem, nothing can really stop ya from changing their names. 

Separately: does your LVS program really need the netlist & layout cells to be the same name? All the ones I’ve used allow specifying the cell names, somehow.
